### ISSUE TITLE
court HP

### ISSUE THREAD

**Issue by Joshurfst** [XcantloadX/PWAAT-Save-Editor#1]
Yo, I am unable to edit court HP, can I only edit court HP when I am out of court?

**Comment by XcantloadX** [comment]
PWAAT saves in different languages are stored separately. Currently only Chinese saves are supported.
It's not a big deal to support other languages. I will do it later on today.

Btw, are there any error messages in the cmd window?

**Comment by XcantloadX** [comment]
I've published a new release. You can try it out again.

**Comment by Joshurfst** [comment]
1. No, I don't remember seeing any errors besides when I tried selecting the steam version of PWAAT(which I don't have)

2. Thanks, I'll try out the new version

**Comment by Joshurfst** [comment]
Alright, yo, I ain't sure if I'm doing something wrong with this, but when I adjust the HP on the file editor, the changes don't get saved to the game itself.

I can add/remove episodes I have access to just fine, I just the changes to the court hp just dont apply to the game.

(Just reread what you said about only Chinese saves being able to be changed, is that still the case?)

**Comment by XcantloadX** [comment]
> (Just reread what you said about only Chinese saves being able to be changed, is that still the case?)

No, the updated version should work for English saves.

> I can add/remove episodes I have access to just fine, I just the changes to the court hp just dont apply to the game.

Have you selected the right save slot? Progress and time information should be shown in the save slot combo box.

Also can you post the save file? The path to save file can be viewed here:
![图片](https://github.com/user-attachments/assets/bd68d788-0eed-4c2a-91ea-7319e17c70b2)

**Comment by Joshurfst** [comment]
I've selected the right save slot, date, time, and progress matched in game.

And here's the save file
![逆转裁判 123 存档工具 8_5_2024 10_53_36 AM](https://github.com/user-attachments/assets/cb964c84-c907-4bd7-8558-8336e066af9e)

**Comment by XcantloadX** [comment]
I have published a new version. This time it should be fixed.

**Comment by Joshurfst** [comment]
> I have published a new version. This time it should be fixed.

yo it works thank you, man. I hope your future projects get more attention, cuz this was really helpful
